### ISSUE TITLE
Unable to query `fom_pbe` in database

### ISSUE THREAD

**Issue by ml-evs** [janosh/dielectrics#1]
Hi @janosh, lovely work on this preprint, really great stuff! Just wanted to compare some of the structures we came up with in a similar project (as of yet unpublished), but I'm struggling to get the computed values out of your atomate db. As far as I can tell the `tasks` collection in your MongoDB atlas does not contain the `fom_pbe` field as suggested in the README? I haven't dug into the archived data yet so will try that when I get a chance.

**Comment by janosh** [comment]
thanks for the kind words! `fom_pbe` (and a few other fields) are computed on the fly in [`df_diel_from_task_coll()`](https://github.com/janosh/dielectrics/blob/e5816da694a1b3e08850063d1c22cefb2d3c8dca/dielectrics/db/fetch_data.py#L98). i'd recommend using that function.

https://github.com/janosh/dielectrics/blob/e5816da694a1b3e08850063d1c22cefb2d3c8dca/dielectrics/db/fetch_data.py#L210-L213

it's a very simple calculation so i saw no need to write the values to the DB but happy to be convinced otherwise.

**Comment by ml-evs** [comment]
> thanks for the kind words! `fom_pbe` (and a few other fields) are computed on the fly in [`df_diel_from_task_coll()`](https://github.com/janosh/dielectrics/blob/e5816da694a1b3e08850063d1c22cefb2d3c8dca/dielectrics/db/fetch_data.py#L98). i'd recommend using that function.
> 
> https://github.com/janosh/dielectrics/blob/e5816da694a1b3e08850063d1c22cefb2d3c8dca/dielectrics/db/fetch_data.py#L210-L213
> 
> it's a very simple calculation so i saw no need to write the values to the DB but happy to be convinced otherwise.

Right, gotcha, I just think the readme example here needs to be updated then as it includes a query for this field. https://github.com/janosh/dielectrics/blob/main/readme.md#L47

**Comment by janosh** [comment]
of course, you're right. how did i miss that? fixed
